Fix packages

diff --git a/modules/so/archlinux/packages/main/dist/.config/packages b/modules/so/archlinux/packages/main/dist/.config/packages
--- a/modules/so/archlinux/packages/main/dist/.config/packages
+++ b/modules/so/archlinux/packages/main/dist/.config/packages
@@ -1,5 +1,7 @@
 #!/bin/sh
 
+set -o pipefail
+
 PAC=(-Syu --noconfirm --needed)
 AUR=(-Syu --noconfirm --needed --sudoloop --skipreview)
 
@@ -23,7 +25,7 @@ PAC+=(xorg-server-xephyr)              # helps testing lightdm on X
 PAC+=(lightdm)                         # lightdm
 PAC+=(lightdm-gtk-greeter)             # lightdm-gtk-greeter
 PAC+=(accountsservice)                 # accountsservice
-AUR+=(keyd-git)                        # keyboard mappings
+# AUR+=(keyd-git)                      # keyboard mappings
 
 # required base software
 PAC+=(systemd)                         # systemd
@@ -44,7 +46,6 @@ PAC+=(xorg-fonts-misc)                 # xorg-fonts-misc
 PAC+=(ttf-nerd-fonts-symbols)          # ttf-nerd-fonts-symbols
 PAC+=(ttf-font-awesome)                # ttf-font-awesome
 AUR+=(ttf-tengwar-annatar)             # tengwar font for elvish
-AUR+=(unipicker)                       # for emojis and symbols
 
 # connectivity packages
 PAC+=(wpa_supplicant)                  # wpa_supplicant for Wifi
@@ -124,7 +125,6 @@ AUR+=(duf-bin)                         # auternative to df
 AUR+=(broot)                           # auternative to tree
 AUR+=(choose)                          # auternative to cut / awk
 PAC+=(tldr)                            # alternative to man
-PAC+=(pping)                           # alternative to ping (with charts)
 PAC+=(procs)                           # alternative to ps
 PAC+=(curlie)                          # alternative to curl
 PAC+=(dog)                             # alternative to dig
@@ -154,7 +154,7 @@ PAC+=(gvfs)                            # network functionality for file managers
 PAC+=(gvfs-smb)                        # smb for thunar
 PAC+=(sshfs)                           # aid thunar to get remote locations done
 AUR+=(sardi-icons)                     # sardi icons
-AUR+=(newaita-icons-git)               # newaita icons
+# AUR+=(newaita-icons-git)             # newaita icons. Not reliable to install via AUR
 # AUR+=(xfwm-axiom-theme)              # axiomd theme. Not reliable to install via AUR
 
 # launchers
@@ -212,14 +212,13 @@ PAC+=(qemu)                            # machine emulator and virtualizer
 PAC+=(virt-manager)                    # libvirt + virt-manager
 PAC+=(firewalld)                       # required to boot the network for qemu
 PAC+=(dnsmasq)                         # required to boot the network for qemu
-PAC+=(ebtables)                        # required to boot the network for qemu
 
 echo "-----> checking AUR packages 👻"
-sudo paru "${AUR[@]}" 2>/dev/null
+paru "${AUR[@]}" 2>/dev/null || (echo "❌ paru packages installation failed" && exit 1)
 
 # update all installed packages and install the ones mentioned above
 # TODO: check if it's still needed after using paru -Syu
-sudo pacman "${PAC[@]}" 2>/dev/null
+sudo pacman "${PAC[@]}" 2>/dev/null || (echo "❌ pacman packages installation failed" && exit 1)
 
 # activate essential services
 SVC=(ntpd.service)                     # ntp service
@@ -232,7 +231,7 @@ SVC+=(libvirtd.service)                # virtualization daemon from libvirt
 SVC+=(bluetooth.service)               # to be able to use bluetooth
 SVC+=(docker.service)                  # docker should be enabled
 SVC+=(reflector.timer)                 # runs periodically to keep mirrors updated
-#SVC+=(lenovo_fix.service)             # throttled service (not working well for now)
+SVC+=(lenovo_fix.service)             # throttled service (not working well for now)
 
 echo "-----> activating services and timers 💪"
 sudo systemctl enable "${SVC[@]}"
@@ -252,33 +251,26 @@ asdf plugin add ruby
 
 asdf plugin update --all
 
-LATEST_ERLANG=$(asdf list all erlang | rg "^\d+\.\d+\.\d+$" | tail -n 1)
-LATEST_ELIXIR=$(asdf list all elixir | rg "^\d+\.\d+\.\d+-otp.*$" | tail -n 1)
-LATEST_GOLANG=$(asdf list all golang | rg "^\d+\.\d+\.\d+$" | tail -n 1)
-LATEST_NODEJS=$(asdf list all nodejs | rg "^\d+\.\d+\.\d+$" | tail -n 1)
-LATEST_PYTHON=$(asdf list all python | rg "^\d+\.\d+\.\d+$" | tail -n 1)
-LATEST_RUBY=$(asdf list all ruby | rg "^\d+\.\d+\.\d+$" | tail -n 1)
+asdf install erlang latest
+asdf global erlang latest
 
-asdf install erlang $LATEST_ERLANG
-asdf global erlang $LATEST_ERLANG
+asdf install elixir latest
+asdf global elixir latest
 
-asdf install elixir $LATEST_ELIXIR
-asdf global elixir $LATEST_ELIXIR
-
-asdf install golang $LATEST_GOLANG
-asdf global golang $LATEST_GOLANG
+asdf install golang latest
+asdf global golang latest
 
 sh ~/.asdf/plugins/nodejs/bin/import-release-team-keyring 2>/dev/null
-asdf install nodejs $LATEST_NODEJS
-asdf global nodejs $LATEST_NODEJS
+asdf install nodejs latest
+asdf global nodejs latest
 
-asdf install python $LATEST_PYTHON
-asdf global python $LATEST_PYTHON
+asdf install python latest
+asdf global python latest
 
-asdf install ruby $LATEST_RUBY
-asdf global ruby $LATEST_RUBY
+asdf install ruby latest
+asdf global ruby latest
 
-# rust is not installed via asdf bicause `rustup` is awesome
+# rust is not installed via asdf because `rustup` is awesome
 rustup toolchain install stable                  # install rust stable
 rustup toolchain install nightly                 # install rust nightly
 rustup default nightly                           # set nightly as default
